#!/bin/bash

iself ()
{
	# taken from /usr/bin/ldd
	lddlibc4 "$1"

	if [[ $? -lt 3 ]]; then
		return 0;
	fi

	# In case of an error punt.
	return 1;
}

pkgs=""
files=""
libs=""

for file in $(qlist ${1}); do
	[[ -x "${file}" && -f "${file}" ]] && files="${files} ${file}"
done

#echo $files

#echo "libs:"

for lib in $(echo ${files} | xargs ldd | grep "=>" | sed -re 's:\(.*\)\s*$::' | sed -re 's:^.*=>::' )
do
	if echo "$lib" | grep -e "[[:alpha:]]" > /dev/null; then
		libs="${libs}${lib} "\\n
	else
		echo "empty:${lib}:"
	fi	
done

libs=$(echo -e ${libs} | sort | uniq)

#echo $libs

for lib in ${libs}; do
#	echo ${lib}
	pkgs="${pkgs}$(qfile -qC ${lib} )"\\n
done

#echo "start"
#echo $pkgs
#echo "stop"

echo -e $pkgs | head --lines=-1 | sort | uniq
#echo -e $pkgs | sort | uniq
