#!/bin/bash
# Used to check reverse rependencies after deleting ebuilds
# 1. delete ebuilds
# 2. run this script with ${CATEGORY}/${PN}

portdir=$(portageq envvar PORTDIR)
cd "${portdir}"
for pkg in $(pquery --raw --restrict-revdep=${1} | sed -re 's/-[^-]+(-r[0-9]+)?$//' | uniq); do
	cd "${portdir}/${pkg}"
	echo "${pkg}"
	pcheck -r portdir -c pkgcore_checks.visibility
done
