#!/bin/bash

if [[ $# == 1 ]]; then
	pkg="$(basename "${PWD}")"
	oldversion="${1}"
elif [[ $# == 2 ]]; then
	pkg="${1}"
	oldversion="${2}"
else
	echo "Usage:"
	echo " <pkg> <old version>"
	exit 1	
fi

#echo $pkg
#echo $oldversion
#exit 0

TMP_DIR="$(mktemp -d /tmp/$(basename ${0})-XXXXXX || exit 1)"
old="${TMP_DIR}/old"
new="${TMP_DIR}/new"

end() {
	rm -v ${TMP_DIR}/{new,old}
	rmdir -v ${TMP_DIR}
	exit ${1}
}

CLEAN_DELAY=0 emerge -1 =${pkg}-${oldversion} || end 1
lsjar $pkg 2>&1 | sort > ${old}
CLEAN_DELAY=0 emerge -1 ${pkg} || end 1
lsjar $pkg 2>&1 | sort > ${new}

echo "diff:"
diff -u ${old} ${new} || end 1
echo "end"

end 0
